# Generated by Django 6.0.8 on 2026-09-11 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BASURA', 'Camión de basura'), ('AGUA', 'Pipa de agua'), ('GAS', 'Gas'), ('MANTENIMIENTO', 'Mantenimiento'), ('GENERAL', 'Aviso general')], max_length=30)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviada', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='notificaciones.aviso')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='residentes.residente')),
            ],
        ),
    ]
