# Generated by Django 6.0.8 on 2026-09-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aviso',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='aviso',
            name='tipo',
            field=models.CharField(choices=[('BASURA', 'Camión de basura'), ('AGUA', 'Pipa de agua'), ('GAS', 'Gas'), ('MANTENIMIENTO', 'Mantenimiento'), ('AREAS_VERDES', 'Áreas verdes'), ('ADMINISTRATIVO', 'Administrativo'), ('GENERAL', 'Aviso general')], max_length=30),
        ),
    ]
