# Generated by Django 6.0.8 on 2026-09-11 18:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
        ('residentes', '0002_alter_residente_options_alter_vivienda_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuota',
            options={'ordering': ['-fecha_inicio', 'vivienda__numero']},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='cuota',
            name='creada',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=12),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='vivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='residentes.vivienda'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cuota',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='pagos.cuota'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], max_length=15),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pago',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pago',
            name='residente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='residentes.residente'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.UniqueConstraint(fields=('vivienda', 'fecha_inicio', 'fecha_fin'), name='cuota_unica_vivienda_semana'),
        ),
    ]
