# Generated by Django 6.0.8 on 2026-09-11 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residentes', '0002_alter_residente_options_alter_vivienda_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paqueteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('AMAZON', 'Amazon'), ('MERCADO_LIBRE', 'Mercado Libre'), ('DHL', 'DHL'), ('FEDEX', 'FedEx'), ('ESTAFETA', 'Estafeta'), ('UPS', 'UPS'), ('OTRO', 'Otro')], max_length=30)),
                ('repartidor', models.CharField(blank=True, max_length=160)),
                ('vehiculo', models.CharField(blank=True, max_length=100)),
                ('placas', models.CharField(blank=True, max_length=20)),
                ('entrada', models.DateTimeField(auto_now_add=True)),
                ('salida', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paqueterias_registradas', to=settings.AUTH_USER_MODEL)),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paqueterias', to='residentes.vivienda')),
            ],
            options={
                'ordering': ['-entrada'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PLOMERIA', 'Plomería'), ('ELECTRICIDAD', 'Electricidad'), ('INTERNET', 'Internet'), ('GAS', 'Gas'), ('JARDINERIA', 'Jardinería'), ('MANTENIMIENTO', 'Mantenimiento'), ('CONSTRUCCION', 'Construcción'), ('MUDANZA', 'Mudanza'), ('OTRO', 'Otro')], max_length=30)),
                ('persona_empresa', models.CharField(max_length=160, verbose_name='Persona o empresa')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('vehiculo', models.CharField(blank=True, max_length=100)),
                ('placas', models.CharField(blank=True, max_length=20)),
                ('entrada', models.DateTimeField(auto_now_add=True)),
                ('salida', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_registrados', to=settings.AUTH_USER_MODEL)),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_recibidos', to='residentes.vivienda')),
            ],
            options={
                'ordering': ['-entrada'],
            },
        ),
    ]
