# Generated by Django 6.0.8 on 2026-09-11 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residentes', '0002_alter_residente_options_alter_vivienda_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoVisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, verbose_name='Nombre del visitante')),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('tipo_identificacion', models.CharField(choices=[('INE', 'INE'), ('PASAPORTE', 'Pasaporte'), ('LICENCIA', 'Licencia'), ('OTRA', 'Otra')], max_length=20, verbose_name='Identificación presentada')),
                ('identificacion_verificada', models.BooleanField(default=True, verbose_name='Identificación verificada')),
                ('vehiculo', models.CharField(blank=True, help_text='Marca / modelo', max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('placas', models.CharField(blank=True, max_length=20)),
                ('entrada', models.DateTimeField(auto_now_add=True)),
                ('salida', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos_registrados', to=settings.AUTH_USER_MODEL)),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='residentes.vivienda')),
            ],
            options={
                'ordering': ['-entrada'],
            },
        ),
    ]
