# Generated by Django 6.0.8 on 2026-09-11 18:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residente',
            options={'ordering': ['apellido_paterno', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='vivienda',
            options={'ordering': ['numero']},
        ),
        migrations.AddField(
            model_name='vivienda',
            name='cuota_semanal',
            field=models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='residente',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='apellido_paterno',
            field=models.CharField(max_length=100, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='numero',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='seccion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sección'),
        ),
    ]
